version: '3'

services:
  # PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html/project

  # Node.js service
  node:
    image: node:18.17.1
    working_dir: /var/www/html/project
    volumes:
      - .:/var/www/html/project

  # MySQL service
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: TASK_MANAGEMENT
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # Vue.js service
  vue:
    image: node:18.17.1
    working_dir: /var/www/html/project
    command: "npm run watch"  # You might need to adjust this command based on your Vue.js project setup
    volumes:
      - .:/var/www/html/project

