version: '3'

services:
  # PHP service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html/myproject/myproject


  # Node.js service
  node:
    image: node:18.17.1
    working_dir: /var/www/html/myproject/myproject
    volumes:
      - .:/var/www/html/myproject/myproject


  # MySQL service
  mysql:
    image: mysql:8
    container_name : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: TASK_MANAGEMENT
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

    # volumes:
    #   - ./mysql-data:/var/lib/mysql
    # command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql


  # Vue.js service
  vue:
    image: node:18.17.1
    working_dir: /var/www/html/myproject/myproject
    command: "npm run build"
    volumes:
      - .:/var/www/html/myproject/myproject


